easy_admin:
    site_name: 'Annuaire'
    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Category
        - App\Entity\Acteur
        - App\Entity\Film
        - App\Entity\Realisateur
        - App\Entity\Genre